# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$character\
$directory\
$git_branch\
$git_status"""

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[➜](bold red) "

[git_branch]
symbol = 'git'
format = '[$symbol:\([$branch](bold red)\)](bold blue) '

[git_status]
# style = "bold yellow"
disabled = true

[directory]
truncation_length = 1

