# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$directory\
$git_branch\
$python\
\n$character"""

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[➜](bold red) "

[git_branch]
symbol = 'git'
format = '[$symbol:\([$branch](bold red)\)](bold blue) '

[directory]
truncation_length = 1

[python]
# Show just "(venvname)" when a venv is active, nothing otherwise
format = "[$symbol(\\($virtualenv\\))]($style) "
style = "bold yellow"

